title: "Min-Hsueh's Home"
logo: /assets/images/about/logo.JPG
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
date_format: "%b %d, %Y"

social_links:
  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=snc23rAAAAAJ&hl=zh-TW" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/minhsuehchiu" }
  - { platform: email,          user_url: "https://www.linkedin.com/in/minhsuehchiu" }